spring:
  application:
    name: datadog-metrics-test
  threads:
    virtual:
      enabled: true

management:
  statsd:
    metrics:
      export:
        flavor: datadog
        enabled: true
  dogstatsd:
    metrics:
      export:
        enabled: true
        queue-size: 5_000_000
        sender-workers: 15
        aggregation-shards: 1
        aggregation-flush-interval: 3_000
        tags:
          env: dev
          app: datadog-metrics-test
logging:
  level:
    io.micrometer: INFO
    io.netty: INFO
    com.timgroup.statsd: INFO
    dogstatsd: INFO
