spring:
  application:
    name: datadog-metrics-test
  threads:
    virtual:
      enabled: true

management:
  statsd:
    metrics:
      export:
        flavor: datadog
        enabled: true
        queue-size: 6_500_000
        sender-workers: 15
        aggregation-shards: 8
        aggregation-flush-interval: 2_000
        constant-tags: "env:dev,app:datadog-metrics-test"
logging:
  level:
    io.micrometer: INFO
    io.netty: INFO
    com.timgroup.statsd: INFO
    dogstatsd: INFO
